#!/usr/bin/env sh
if [ ! $2 ]
then 
  node scripts/check-version 
else
  node scripts/check-version -v $2
fi	
PACKAGE_VERSION=$(cat package.json | grep version | head -1 | awk -F: '{ print $2 }' | sed 's/[\",]//g' | tr -d '[[:space:]]')

npm config set registry https://registry.npmjs.org/

git add .
git commit -m  "chore(release) version: "$PACKAGE_VERSION" ""commit:""$1"
git push -u

npm_config_report=false npm run build
npm publish --access public --registry=https://registry.npmjs.org/
